### ISSUE TITLE
failing to compile package

### ISSUE THREAD

**Issue by PaoloSupino** [aristanetworks/openconfigbeat#4]
I'm trying to compile the latest version of openconfigbeat. When I run make I get the following error:
$ make 
go build
main.go:12:2: cannot find package "github.com/aristanetworks/openconfigbeat/beater" in any of:
	/usr/lib/golang/src/github.com/aristanetworks/openconfigbeat/beater (from $GOROOT)
	/home/me/src/src/github.com/aristanetworks/openconfigbeat/beater (from $GOPATH)
make: *** [openconfigbeat] Error 1

The directory and the file do exist: 
$ ls -l /home/me/src/github.com/aristanetworks/openconfigbeat/beater/
total 8
-rw-rw-r--. 1 paolo paolo 4359 Feb 15 17:22 openconfigbeat.go
$ 

My build environment is RedHat Linux 6.8 with golang installed from Epel repository (go version go1.7.4 linux/amd64). What am I doing wrong?

**Comment by 7AC** [comment]
The workspace needs to be in `$GOPATH/src/github.com/aristanetworks/openconfigbeat`, but sounds like you figured it out already. I think there's a bug in the README caused by the generator itself, I left a comment about it:

https://github.com/elastic/beats/commit/15991e4f098d8cf6be8a114068ab31711862a2f5#commitcomment-20898996
